### ISSUE TITLE
cant get  packages

### ISSUE THREAD

**Issue by UnluckyY1** [devdennysegura/flutter-netflix-clone#1]
C:\src\flutter-netflix-clone-master>flutter packages get

"Because netflix_clone depends on fluro from path which doesn't exist (could not find package fluro at "..\..\FlutterLibs\fluro"), version solving failed.
Running "flutter packages get" in flutter-netflix-clone-master..."
pub get failed (66)

**Comment by UnluckyY1** [comment]
> C:\src\flutter-netflix-clone-master>flutter packages get
> 
> "Because netflix_clone depends on fluro from path which doesn't exist (could not find package fluro at "....\FlutterLibs\fluro"), version solving failed.
> Running "flutter packages get" in flutter-netflix-clone-master..."
> pub get failed (66)
i found a quick fix by going to the 'pubspec.yaml' and change fluro:
    path: ../../FlutterLibs/fluro
to fluro:
   git: git://github.com/theyakka/fluro.git

**Comment by devdennysegura** [comment]
already this problem has fixed
