### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by UnluckyY1** [devdennysegura/flutter-netflix-clone#2]
Compiler message:
lib/src/pages/summary/state.dart:11:7: Error: No named parameter with the name 'object'.
      object: {'type': type},
      ^^^^^^
lib/src/pages/summary/state.dart:21:7: Error: No named parameter with the name 'object'.
      object: {'match': match, 'show': item},
      ^^^^^^
lib/src/pages/summary/state.dart:33:9: Error: No named parameter with the name 'object'.
        object: {'title': 'Unforgettable'},
        ^^^^^^
Compiler failed on C:\src\flutter-netflix-clone-master\lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        46.7s
Gradle task assembleDebug failed with exit code 1

**Comment by alexsandro-12** [comment]
Help

**Comment by ShaharLahav** [comment]
help

**Comment by smuh96** [comment]
any solution?

**Comment by devdennysegura** [comment]
let me watch flutter doctor command result

**Comment by devdennysegura** [comment]
update pubspec plugin "Fluro" to my forked "Fluro project clone" https://github.com/devdennysegura/fluro

**Comment by esQmo** [comment]
This fork prevent the build with Flutter >= 1.12 and causes #8
