### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by kentaro989** [devdennysegura/flutter-netflix-clone#8]
i got this error

/C:/src/flutter/.pub-cache/git/fluro-d1a5e9c8aa02185e9533f1e8246d4e4938bd9cd5/lib/src/router.dart:38:47: Error: This expression has type 'void' and can't be used.
  bool pop(BuildContext context) => Navigator.pop(context);
                                              ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

how to fix it?

**Comment by esQmo** [comment]
You need Fluro1.6.0+ if  you're using Flutter >= 1.12. Fixed mine by using Fluro from the original repo, not the fork from this project
